// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElGrid: typeof import('element-plus/es')['ElGrid']
    ElRow: typeof import('element-plus/es')['ElRow']
    Nav: typeof import('./src/components/nav.vue')['default']
  }
}

export { }
